// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGuDtG-Ri8mEqgLIzCo7USGlyOMnZsUIs',
    appId: '1:36684990003:web:4b3034eb5730372418c546',
    messagingSenderId: '36684990003',
    projectId: 'notif-22346',
    authDomain: 'notif-22346.firebaseapp.com',
    storageBucket: 'notif-22346.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGE0FKlbQE2JUo8N1R9AOx94zhyYmXvfM',
    appId: '1:36684990003:android:07af31a52213dff618c546',
    messagingSenderId: '36684990003',
    projectId: 'notif-22346',
    storageBucket: 'notif-22346.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6xLufzqYsQwA82i1oWFN5N4tSIu5y-5I',
    appId: '1:36684990003:ios:a6f2b985ab0185bb18c546',
    messagingSenderId: '36684990003',
    projectId: 'notif-22346',
    storageBucket: 'notif-22346.firebasestorage.app',
    iosBundleId: 'com.example.sapeurPompier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6xLufzqYsQwA82i1oWFN5N4tSIu5y-5I',
    appId: '1:36684990003:ios:a6f2b985ab0185bb18c546',
    messagingSenderId: '36684990003',
    projectId: 'notif-22346',
    storageBucket: 'notif-22346.firebasestorage.app',
    iosBundleId: 'com.example.sapeurPompier',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGuDtG-Ri8mEqgLIzCo7USGlyOMnZsUIs',
    appId: '1:36684990003:web:593851cbe01bd20318c546',
    messagingSenderId: '36684990003',
    projectId: 'notif-22346',
    authDomain: 'notif-22346.firebaseapp.com',
    storageBucket: 'notif-22346.firebasestorage.app',
  );
}
